{% set name = "pyift" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyift-{{ version }}.tar.gz
  sha256: 37a2c11a4d81d15429c61d0ae8110d00b5e6f303c7e9b90d3ca4305516cb4618

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools-scm
    - numpy
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  imports:
    - pyift
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyift/pyift
  summary: Python Image Foresting Transform Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - JoOkuma
